# Generated by Django 4.1.5 on 2023-01-26 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accounts_crate_table_accounts_sku_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 26, 12, 22, 5, 240485)),
        ),
    ]
