# Generated by Django 4.1.5 on 2023-01-26 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cratetable',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 26, 12, 17, 15, 828990)),
        ),
        migrations.AlterField(
            model_name='skutable',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 26, 12, 17, 15, 828990)),
        ),
    ]
