# Generated by Django 4.1.5 on 2023-01-26 06:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_cratetable_creation_alter_skutable_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cratetable',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.skutable'),
        ),
        migrations.AlterField(
            model_name='cratetable',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 26, 12, 24, 41, 763667)),
        ),
        migrations.AlterField(
            model_name='skutable',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 26, 12, 24, 41, 762664)),
        ),
    ]
